### ISSUE TITLE
Do 'chmod' on directory 'backups' to reduce access

### ISSUE THREAD

**Issue by DrChr** [tychoish/.emacs.d#3]
Hi,

Perhaps the directory `backups/` should not be accessible by everyone?

```
drwxrwxr-x   2 chr chr   4096 aug 29 07:17 backups/
```
Rationale: The directory will contain files that you maybe don't want every user to be able to see.

**Comment by tychoish** [comment]
Ah I didn't notice that! As far as I know, this directory gets created by emacs itself (and this functionality is part of emacs.) While it's easy enough to change the permissions of the directory, I believe the backup files themselves inherit the permissions of the files that they mirror, so while I can make the directory 700, I can't (and wouldn't want to) change the permissions of the files within the directory.

I have a solution that appears to work, so I've pushed that up!

Cheers!
