### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by neco0274** [tychoish/.emacs.d#5]
Error (use-package): tychoish-core/:config: Symbol’s function definition is void: package-archive-contents

**Comment by tychoish** [comment]
Interesting! I've not seen this on my own instance, and I just checked and made sure that everything was up to date. While the core code is up to date, I think I had omitted to commit new versions of the elpa sub-repo. If you're using this, then a git pull might fix it. 


To be honest, this seems like it's likely a problem with dependencies and packages, which makes the theory about the elpa repo out of date a viable theory. 
My usual questions for debug this kind of problem are: 
- what version of emacs are you running?
- are you connected to the internet when starting emacs?
- can you post any debug output from starting emacs with `emacs --debug-init`?
- did you check out my elpa sub repo? 

Sorry you're having this problem, but I hope we can clear this up soon!

**Comment by neco0274** [comment]
Thanks for your fast replay.

I'm Japanese so I'm sorry for my poor English

1) GNU Emacs 27.1

2) Inter net is connected at start emacs
  and use below commands for install

-----------------------------------------------------------------------------
    cd ~
    rm -rf ~/.emacs.d
    git clone --recurse-submodules ***@***.***:tychoish/.emacs.d.git
~/.emacs.d/
-----------------------------------------------------------------------------

4) Below Backtrace of Debugger at execute "emacs --debug-init"

Sincerely :-)

---------------------------------------------------------------------------
Debugger entered--Lisp error: (void-function package-archive-contents)
  (package-archive-contents)
  (if (package-archive-contents) nil (package-refresh-contents))
  eval-buffer(#<buffer  *load*-468259> nil
"/home/neco/.emacs.d/user/.neco.el" nil t)  ; Reading at buffer position 495
  load-with-code-conversion("/home/neco/.emacs.d/user/.neco.el"
"/home/neco/.emacs.d/user/.neco.el" nil t)
  require(\.neco)
  (let ((time (current-time))) (require (intern (string-remove-suffix ".el"
fn))) (tychoish--threshold-logger 0.1 (time-to-seconds (time-since time))
(format "loading user config [%s]" fn)))
  (progn (let ((time (current-time))) (require (intern
(string-remove-suffix ".el" fn))) (tychoish--threshold-logger 0.1
(time-to-seconds (time-since time)) (format "loading user config [%s]"
fn))))
  (if (string-match-p "\\.el$" fn) (progn (let ((time (current-time)))
(require (intern (string-remove-suffix ".el" fn)))
(tychoish--threshold-logger 0.1 (time-to-seconds (time-since time)) (format
"loading user config [%s]" fn)))))
  (lambda (fn) (if (string-match-p "\\.el$" fn) (progn (let ((time
(current-time))) (require (intern (string-remove-suffix ".el" fn)))
(tychoish--threshold-logger 0.1 (time-to-seconds (time-since time)) (format
"loading user config [%s]" fn))))))(".neco.el")
  mapc((lambda (fn) (if (string-match-p "\\.el$" fn) (progn (let ((time
(current-time))) (require (intern (string-remove-suffix ".el" fn)))
(tychoish--threshold-logger 0.1 (time-to-seconds (time-since time)) (format
"loading user config [%s]" fn)))))) ("." ".." ".gitkeep" ".neco.el"))
  (progn (add-to-list 'load-path dirname) (mapc #'(lambda (fn) (if
(string-match-p "\\.el$" fn) (progn (let (...) (require ...)
(tychoish--threshold-logger 0.1 ... ...))))) (directory-files dirname)))
  (if (file-accessible-directory-p dirname) (progn (add-to-list 'load-path
dirname) (mapc #'(lambda (fn) (if (string-match-p "\\.el$" fn) (progn (let
... ... ...)))) (directory-files dirname))))
  (let ((dirname (concat (expand-file-name user-emacs-directory) "user")))
(if (file-accessible-directory-p dirname) (progn (add-to-list 'load-path
dirname) (mapc #'(lambda (fn) (if (string-match-p "\\.el$" fn) (progn
...))) (directory-files dirname)))) t)
  tychoish-setup-user-local-config()
  (progn (tychoish-setup-global-modes) (tychoish-setup-modeline)
(tychoish-setup-user-local-config) t)
  (condition-case err (progn (tychoish-setup-global-modes)
(tychoish-setup-modeline) (tychoish-setup-user-local-config) t) ((debug
error) (funcall use-package--warning0 :config err)))
  (if (not (require 'tychoish-core nil t)) (display-warning 'use-package
(format "Cannot load %s" 'tychoish-core) :error) (condition-case err (progn
(tychoish-setup-global-modes) (tychoish-setup-modeline)
(tychoish-setup-user-local-config) t) ((debug error) (funcall
use-package--warning0 :config err))))
  (condition-case err (if (not (require 'tychoish-core nil t))
(display-warning 'use-package (format "Cannot load %s" 'tychoish-core)
:error) (condition-case err (progn (tychoish-setup-global-modes)
(tychoish-setup-modeline) (tychoish-setup-user-local-config) t) ((debug
error) (funcall use-package--warning0 :config err)))) ((debug error)
(funcall use-package--warning0 :catch err)))
  eval-buffer(#<buffer  *load*> nil "/home/neco/.emacs.d/init.el" nil t)  ;
Reading at buffer position 1570
  load-with-code-conversion("/home/neco/.emacs.d/init.el"
"/home/neco/.emacs.d/init.el" t t)
  load("/home/neco/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode
0xc3dd51>) #f(compiled-function () #<bytecode 0xc3dd65>) t)
  command-line()
  normal-top-level()

---------------------------------------------------------------------------





2021年4月25日(日) 0:19 Sam Kleinman ***@***.***>:

**Comment by neco0274** [comment]
I'm sorry, the following

I found out that it was my mistake because of my custom script

Thanks to the emacs options you taught me

Thank you very much !!


2021年4月25日(日) 4:15 中村英世 ***@***.***>:

**Comment by tychoish** [comment]
Glad to hear that it's fixed! Hope you continue to enjoy.
